### PR TITLE
Add copyright headers

### PR DESCRIPTION
**Pull request by jdgwartney**

### CODE REVIEW

**Comment by gokumar** [comment]
@jdgwartney Could you please resolve conflicts and merge. We have merged your previous pull request after validating. Pleae merge these conflicts and merge.

**Comment by gokumar** [comment]
@jdgwartney, Could you please do the needful?

**Comment by gokumar** [comment]
Since, I did not get response. I am closing this pull request. Adding the copyrights in the fresh commit.

**Comment by dgwartney** [comment]
I was on PTO last week.

**Comment by dgwartney** [comment]
Not sure why it would have been that difficult to merge these.

**Comment by gokumar** [comment]
I feel the same. But, when i tried to resolve conflicts and merge, it was giving me permissions error.

**Pull request closed without merging**
